### ISSUE TITLE
AsyncAppender causing OOM after updating to 3.0.7.RELEASE

### ISSUE THREAD

**Issue by jansyk13** [reactor/reactor-addons#118]
Hello,

after updating reactor-logback from 2.0.8.RELEASE to 3.0.7.RELEASE, we started having issues with application getting into OOM. After inspecting memory dump, there is about 90% of heap allocated by the log appender(ring buffer in WorkQueueProcessor). The ring buffer is fully allocated at max capacity(default 1024*1024). The heap size is rather small (256 MB).

I have noticed small change in code - https://github.com/reactor/reactor-addons/commit/797e9e7bc84f13f22901bcd335a0743618a2b446#diff-92015f3933e75ee338e1cad889985f2cR114 . But I doubt that this is a cause. Possible root cause could be in reactor-core. IMHO it looks like that log events are not consumed fast enough(we have syslog appender underneath it, either it is slow or the event loop thread is not getting enough CPU time).  Any ideas?

We have downgraded back to 2.0.8.RELEASE and it works fine. Any help would be appreciated.

Thanks
Jan

**Comment by smaldini** [comment]
Have you given a try to 3.1.0.RC1 by any chance ? There seems to be an issue with the consuming size indeed.

**Comment by jansyk13** [comment]
Ok, I will give a try. What is estimated date for 3.1.1 release?

**Comment by simonbasle** [comment]
@jansyk13 3.1.0.RELEASE should be out today

**Comment by jansyk13** [comment]
I have run a perf test on my app and it ended up in OOM again(with 3.1.0.RC1). I got few NoClassDefFoundErrors also this time(inner Netty class), but I think it is because JVM fails to initialize static block in the class.

The application died after two minutes of mediocre traffic(2k req/sec). Later today I will try to isolate and recreate the issue in the sandbox. When I have the reproducer I will post the code.

**Comment by smaldini** [comment]
Do you have a use case to reproduce unfortunately apart from a couple minor tweaks i haven't managed to reproduce it :(

**Comment by smaldini** [comment]
Feel free to re-open with a test case
